### ISSUE TITLE
More Commands 

### ISSUE THREAD

**Issue by cylon147** [ilker-aktuna/androidTV_keyboard_withRestAPI#2]
I love the way you have implemented this.

Is there any way we can pass more Keycodes?
Like: http://192.168.225.139:5000/Keycode=139

it will be great if we have Channel Up and Channel Down Commands as well.

Also Launching the App like Netflix, Prime Video.

Would love to contribute more.

**Comment by ilker-aktuna** [comment]
sure , but possibilities are too much. I need to understand what is required and for what kind of purpose. do you just want to send the keycodes as parameter ?

**Comment by cylon147** [comment]
yes, Keycode as Parameter will work as some of the codes are embedded in BE remote of my Android Box. I would love a way to fire these commands.

**Comment by ilker-aktuna** [comment]
ok. I've added this functionality now.
New release will be available on Google Play Store in a few hours.
You can use it with integer format like:
/keycode=44
or with keycode names like:
/keycode=KEYCODE_P
list of available keycodes are here:
https://developer.android.com/reference/android/view/KeyEvent.html

but I could not make it work for SHIFT , CAPS_LOCK and some others. I don't know why.
Since I don't have much time, I didn't work on it. But if you need some special keycode, we can work on it later.

As a bonus, I've added a /sendtext endpoint.
You can use it like:

/sendtext=test.me

not all characters are possible. but it works for simple requirements.

**Comment by cylon147** [comment]
Thanks You so much:)
